### ISSUE TITLE
Clarify the use of the NDP option

### ISSUE THREAD

**Issue by JKRhb** [namib-project/draft-coap-mud#3]
It should be discussed where the NDP option is supposed to be included. Should it only be sent in Router Solicitations? Or could it be used in other message types as well:

- Neighbor Solicitation (type 135)
- Neighbor Advertisement (type 136)
- Redirect (type 137)

My current impression is that these message types are not suitable for MUD URLs, but I might be wrong here.

**Comment by pulsastrix** [comment]
Is this still relevant? If so, it should probably be transferred to [JKRhb/mud-ndp-option](https://github.com/JKRhb/mud-ndp-option), I assume.

**Comment by JKRhb** [comment]
Hmm, seems as if you can only move the issue to a repository within the same organization/user. I will close it for now here and may either reopen it over at [JKRhb/mud-ndp-option](https://github.com/JKRhb/mud-ndp-option) or, alternatively, move the NDP repo to this organization and then transfer the issue.
